name: eshop_multivendor
description: eShop Multivendor App
publish_to: "none"

version: 2.5.0+1


environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  http: ^0.13.4
  shared_preferences: ^2.0.15
  connectivity_plus: ^4.0.1
  jaguar_jwt: ^3.0.0
  flutter_local_notifications: ^14.1.0
  path_provider: ^2.0.10
  firebase_messaging: ^14.2.0
  flutter_rating_bar: ^4.0.1
  photo_view: ^0.14.0
  firebase_auth: ^4.2.3
  sms_autofill: ^2.2.0
  #intl: ^0.17.0
  google_maps_flutter: ^2.2.2
  geolocator: ^9.0.2
  file_picker: ^5.2.4
  shimmer: ^3.0.0
  geocoding: ^2.0.2
  razorpay_flutter: ^1.3.0 #^1.3.4
  flutter_paystack: ^1.0.7
  flutter_html_to_pdf: ^0.7.0
  permission_handler: ^10.2.0
  in_app_review: ^2.0.6
  firebase_dynamic_links: ^5.0.10
  open_filex: ^4.3.2
  provider: ^6.0.5
  share_plus: ^7.0.1
  firebase_core: ^2.4.0
  video_player: ^2.4.10
  flutter_svg: ^2.0.2
  paytm: ^3.0.1
  youtube_player_flutter: ^8.1.2
  package_info_plus: ^4.0.1
  url_launcher: ^6.1.7
  sqflite: ^2.2.2
  version: ^3.0.2
  flutter_downloader: ^1.9.1
  speech_to_text: ^6.1.1
  tuple: ^2.0.1
  lottie: ^2.1.0
  flutter_stripe: ^9.0.0+1
  flutter_widget_from_html: ^0.10.0
  flutter_html: ^3.0.0-alpha.6
  my_fatoorah: ^3.1.0
  webview_flutter: ^4.0.5
  intl_phone_field: ^3.1.0
  google_sign_in: ^6.1.0
  sign_in_with_apple: ^5.0.0
  crypto: ^3.0.1
  flutter_styled_toast: ^2.1.3
  intl: ^0.18.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^2.0.1

dependency_overrides:
  intl: ^0.18.1
  chewie:
    git:
      url: https://github.com/mdeimert/chewie.git
      ref: master

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/png/
    - assets/images/svg/
    - assets/animation/
    - lib/Language/
    - assets/eShop.db

  fonts:
    - family: ubuntu
      fonts:
        - asset: assets/font/Ubuntu-Regular.ttf
